title: eleganttip.css
description: Provide an elegant and configurable tips message block (tooltips) on your DOM element while mouse hover or focus on. (pure CSS)
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
